INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(1,'andy@example.com');
INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(2,'Sat@example.com');
INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(3,'Aar@example.com');
INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(4,'john@example.com');
INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(5,'common@example.com');
INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(6,'lisa@example.com');
INSERT INTO T_USER(ID,USER_EMAIL_ADDRESS) VALUES(7,'kate@example.com');

INSERT INTO T_USER_FRIENDS(ID,USER_EMAIL_ADDRESS,FRIEND_EMAIL_ADDRESS,SUBSCRIBED) VALUES(1,'andy@example.com','common@example.com','Yes');
INSERT INTO T_USER_FRIENDS(ID,USER_EMAIL_ADDRESS,FRIEND_EMAIL_ADDRESS,SUBSCRIBED) VALUES(2,'andy@example.com','Aar@example.com','Yes');
INSERT INTO T_USER_FRIENDS(ID,USER_EMAIL_ADDRESS,FRIEND_EMAIL_ADDRESS,SUBSCRIBED) VALUES(3,'john@example.com','common@example.com','No');
INSERT INTO T_USER_FRIENDS(ID,USER_EMAIL_ADDRESS,FRIEND_EMAIL_ADDRESS,SUBSCRIBED) VALUES(5,'john@example.com','lisa@example.com','Yes');
INSERT INTO T_USER_FRIENDS(ID,USER_EMAIL_ADDRESS,FRIEND_EMAIL_ADDRESS,SUBSCRIBED) VALUES(6,'john@example.com','kate@example.com','Yes');