create sequence T_USER_SEQ START WITH 9;
create sequence T_USER_FRIENDS_SEQ START WITH 9;
create sequence T_USER_NOTIFICATION_SEQ START WITH 2;
create table T_USER (ID integer , USER_EMAIL_ADDRESS VARCHAR(200) primary key);
create table T_USER_FRIENDS (ID integer identity primary key, USER_EMAIL_ADDRESS VARCHAR(200), FRIEND_EMAIL_ADDRESS VARCHAR(200), SUBSCRIBED VARCHAR(100));
create table T_USER_NOTIFICATION (ID integer identity primary key, USER_EMAIL_ADDRESS VARCHAR(200) , USER_MESSAGE VARCHAR(4000));
-- ALTER TABLE T_USER_FRIENDS ADD FOREIGN KEY (USER_EMAIL_ADDRESS) REFERENCES T_USER(USER_EMAIL_ADDRESS);
ALTER TABLE T_USER_NOTIFICATION ADD FOREIGN KEY (USER_EMAIL_ADDRESS) REFERENCES T_USER(USER_EMAIL_ADDRESS);